{"name": "test_vwo_login_positive", "status": "broken", "statusDetails": {"message": "seleniumpagefactory.Pagefactory.ElementNotVisibleException: An exception of type TimeoutException occurred. With Element -: username - locator: (css selector, #login-username)", "trace": "self = <tests.pageObjects.pageFactory.loginpage_pf.LoginPage object at 0x000002493EEF1970>, loc = 'username'\n\n    def __getattr__(self, loc):\n    \n        if self.mobile_test == True:\n            if loc in self.locators.keys():\n                element = self.find_element_by_accessibility_id(self.locators[loc][1])\n                return element\n        else:\n            if loc in self.locators.keys():\n                locator = (self.TYPE_OF_LOCATORS[self.locators[loc][0].lower()], self.locators[loc][1])\n                try:\n                    element = WebDriverWait(self.driver, self.timeout).until(\n                        EC.presence_of_element_located(locator)\n                    )\n                except (StaleElementReferenceException, NoSuchElementException, TimeoutException) as e:\n                    raise ElementNotFoundException(\n                        \"An exception of type \" + type(e).__name__ +\n                        \" occurred. With Element -: \" + loc +\n                        \" - locator: (\" + locator[0] + \", \" + locator[1] + \")\"\n                    )\n    \n                try:\n>                   element = WebDriverWait(self.driver, self.timeout).until(\n                        EC.visibility_of_element_located(locator)\n                    )\n\n.venv\\Lib\\site-packages\\seleniumpagefactory\\Pagefactory.py:69: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"2df47802804f4ad9e7f4f4c0b3d7ecc4\")>\nmethod = <function visibility_of_element_located.<locals>._predicate at 0x000002493EFBA8E0>, message = ''\n\n    def until(self, method: Callable[[D], Union[Literal[False], T]], message: str = \"\") -> T:\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message:\n\n.venv\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py:105: TimeoutException\n\nDuring handling of the above exception, another exception occurred:\n\nself = <tests.test.vwoLoginTests.test_vwo_login_pf.TestVWOLogin object at 0x000002493EEF3A10>\nsetup = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"2df47802804f4ad9e7f4f4c0b3d7ecc4\")>\n\n    @pytest.mark.usefixtures(\"setup\")\n    @pytest.mark.qa\n    def test_vwo_login_positive(self, setup):\n        LOGGER = logging.getLogger(__name__)\n        LOGGER.info(\"Starting the Testcase\")\n        driver = setup\n        driver.get(Constants.app_url())\n        login_page = LoginPage(driver)\n>       login_page.login_to_vwo(username=self.username, pwd=self.password)\n\ntests\\test\\vwoLoginTests\\test_vwo_login_pf.py:44: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \ntests\\pageObjects\\pageFactory\\loginpage_pf.py:33: in login_to_vwo\n    self.username.set_text(username)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <tests.pageObjects.pageFactory.loginpage_pf.LoginPage object at 0x000002493EEF1970>, loc = 'username'\n\n    def __getattr__(self, loc):\n    \n        if self.mobile_test == True:\n            if loc in self.locators.keys():\n                element = self.find_element_by_accessibility_id(self.locators[loc][1])\n                return element\n        else:\n            if loc in self.locators.keys():\n                locator = (self.TYPE_OF_LOCATORS[self.locators[loc][0].lower()], self.locators[loc][1])\n                try:\n                    element = WebDriverWait(self.driver, self.timeout).until(\n                        EC.presence_of_element_located(locator)\n                    )\n                except (StaleElementReferenceException, NoSuchElementException, TimeoutException) as e:\n                    raise ElementNotFoundException(\n                        \"An exception of type \" + type(e).__name__ +\n                        \" occurred. With Element -: \" + loc +\n                        \" - locator: (\" + locator[0] + \", \" + locator[1] + \")\"\n                    )\n    \n                try:\n                    element = WebDriverWait(self.driver, self.timeout).until(\n                        EC.visibility_of_element_located(locator)\n                    )\n                except (StaleElementReferenceException, NoSuchElementException, TimeoutException) as e:\n>                   raise ElementNotVisibleException(\n                        \"An exception of type \" + type(e).__name__ +\n                        \" occurred. With Element -: \" + loc +\n                        \" - locator: (\" + locator[0] + \", \" + locator[1] + \")\"\n                    )\nE                   seleniumpagefactory.Pagefactory.ElementNotVisibleException: An exception of type TimeoutException occurred. With Element -: username - locator: (css selector, #login-username)\n\n.venv\\Lib\\site-packages\\seleniumpagefactory\\Pagefactory.py:73: ElementNotVisibleException"}, "start": 1726209698961, "stop": 1726209712532, "uuid": "c2b8b7ef-9d20-4c63-8202-d7a866dfb805", "historyId": "6109efe96f903dc20f391c57b0ade122", "testCaseId": "6109efe96f903dc20f391c57b0ade122", "fullName": "tests.test.vwoLoginTests.test_vwo_login_pf.TestVWOLogin#test_vwo_login_positive", "labels": [{"name": "feature", "value": "Login Test"}, {"name": "epic", "value": "VWO App"}, {"name": "tag", "value": "qa"}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests.test.vwoLoginTests"}, {"name": "suite", "value": "test_vwo_login_pf"}, {"name": "subSuite", "value": "TestVWOLogin"}, {"name": "host", "value": "Chaitra"}, {"name": "thread", "value": "28656-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test.vwoLoginTests.test_vwo_login_pf"}]}